# SITE CONFIGURATION
baseurl: "" # Set it to "" if use for personal site. The subpath of your site, e.g. /blog/
url: "http://www.mister-yes.com" # the base hostname & protocol for your site
# HOST && PORT
host: 192.168.78.130
port: 80



imageurl: "https://source.unsplash.com/category/nature/2600x500" #"https://unsplash.it/2600/500?random"






# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Mr.Yes's Blog
  #avatar: avatar.png
  hometitle: 首页 #display on navigation menu.
  yoursitetitle: Mr.Yes
  gravatar: # Email MD5 hash
  description: "used by search engines" # used by search engines
  visiblewords: 300
  # Header and footer text
  header_text: >
     HELLO EVERY BODY!

  header_text_feature_image: img/sample_feature_img.png
  place_holder_image: img/sample_feature_img.png
  footer_text: >
   <a href="http://www.mister-yes.com">Mr.Yes</a> 

 





  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: false

# PAGINATION
#enforce_ssl: "fengzhichu.com"
paginate: 5
paginate_path: "blog/page:num"
permalink: blog/:title/ 



# BUILD SETTINGS  later see
markdown: redcarpet
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed



gems:
  - jekyll-paginate


